version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data

  redis_test:
    image: redis:latest
    container_name: redis_test
    ports:
      - "6381:6379"
  